org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

mod_version=0.3.0

mod_id=distant_players
mod_name=Render Distant Players
mod_license=MIT
mod_authors=1whohears, kawaiicakes
mod_description=Renders players and their vehicles, from beyond the render distance.

maven_group=com.onewhohears.distant_players
archives_name=distant_players
enabled_platforms = fabric,forge

homepage=https://github.com/1whohears
sources=https://github.com/1whohears/RenderDistantPlayers
issue_tracker=https://github.com/1whohears/RenderDistantPlayers/issues

minecraft_version=1.20.1
minecraft_version_range=[1.20.1)

architectury_version = 9.2.14

fabric_loader_version = 0.17.2
fabric_api_version = 0.92.6+1.20.1

forge_version=1.20.1-47.4.0
forge_version_range=[47,)
forge_loader_version_range=[47,)

onewholibs_version=2.0.12